TaskTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.tasks.urls')),
    path('profile/', include('apps.accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.urls import path
from .views import show_profile

app_name = 'users'

urlpatterns = [
    path('', show_profile, name='show_profile'),
]

apps/tasks/urls.py
from django.urls import path
from .views import list_tasks, create_task, edit_task, detail_task, completed_list_tasks, delete_task

app_name = 'tasks'

urlpatterns = [
    path('', list_tasks, name='task_list'),
    path('create/', create_task, name='create_task'),
    path('completed/', completed_list_tasks, name='completed_list_tasks'),
    path('edit/<uuid:uuid>/', edit_task, name='edit_task'),
    path('<uuid:uuid>/', detail_task, name="detail_task"),
    path('edit/<uuid:uuid>/delete/', delete_task, name='delete_task'),
]

apps/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from PIL import Image


from .manager import CustomUserManager

class User(AbstractBaseUser):
    login = models.CharField(max_length=128, unique=True)
    email = models.EmailField(max_length=256, unique=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = CustomUserManager()

    USERNAME_FIELD = 'login'
    REQUIRED_FIELDS = ['email',]


    def __str__(self):
        return self.login


    def has_perm(self, perm, obj=None):
        return True


    def has_module_perms(self, app_label):
        return True


    @property
    def is_staff(self):
        return self.is_admin

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Profile(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='username')
    tasks_completed = models.PositiveIntegerField(default=0)
    tasks_active = models.PositiveIntegerField(default=0)
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    telegram = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.user.login

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.avatar.path)
        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

apps/tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model
from uuid import uuid4
from django.urls import reverse


User = get_user_model()

class Task(models.Model):
    STATUS_CHOICES  = (
        ('not_started', "Не начата"),
        ('started', 'Начата'),
        ('completed', 'Завершена'),
        ('reopened', 'Переоткрыта'),
    )
    uuid = models.UUIDField(default=uuid4, editable=False)
    name = models.CharField(max_length=128)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(auto_now=True, blank=True)
    date_updated = models.DateTimeField(auto_now=True, blank=True)
    status = models.CharField(
        max_length=30,
        choices=STATUS_CHOICES,
        default= 'not_started'
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    executor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='executor' )
    priority = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse('tasks:detail_task', args=[str(self.uuid)])

    def __str__(self):
        return f"Task: {self.name} -- {self.uuid}"

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        ordering = ['-priority']

apps/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django import forms

User = get_user_model()

class LoginForm(AuthenticationForm):
    login = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={"class": "form-control mb-1", 'placeholder': 'Username'}))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(
                                   attrs={"class": "form-control mb-1", 'placeholder': 'Password'}))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['login', 'password', 'remember_me']

apps/tasks/forms.py
from django import forms
from .models import Task


class TaskCreationForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('name', 'description', 'author', 'executor', 'priority')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off',
            })

class TaskEditForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('name', 'description', 'author', 'executor', 'priority', 'status')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off',
            })

apps/accounts/views.py
from django.contrib.auth.views import LoginView
from .forms import LoginForm
from django.shortcuts import render, get_object_or_404
from apps.tasks.models import Task
from .models import Profile, User

def show_profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    tasks = Task.objects.filter(executor=request.user)
    context = {
        'profile': profile,
        'tasks': tasks,
    }

    return render(request, 'accounts/profile.html', context=context)

class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            self.request.session.set_expiry(0)
            self.request.session.modified = True

        return super(CustomLoginView, self).form_valid(form)

apps/tasks/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from .models import Task
from .forms import TaskCreationForm, TaskEditForm

@login_required
def list_tasks(request):
    tasks = Task.objects.exclude(status='completed')
    context = {
        'tasks': tasks,
    }
    return render(request, template_name='tasks/task_list.html', context=context)


@login_required
def completed_list_tasks(request):
    tasks = Task.objects.filter(status='completed')
    context = {
        'tasks': tasks,
    }
    return render(request, template_name='tasks/completed_task_list.html', context=context)

@login_required
def edit_task(request, uuid):
    try:
        task = get_object_or_404(Task, uuid=uuid)
    except:
        raise Http404('Такой задачи нет')

    if request.method == "POST":
        form = TaskEditForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect(f'/')

    else:
        form = TaskEditForm(instance=task)
        context = {
            'form': form,
        }
        return render(request, template_name='tasks/task_edit.html', context=context)

@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskCreationForm(request.POST)
        form.save()
        return redirect('/')

    else:
        form = TaskCreationForm()
        context = {
            'form': form,
        }
        return render(request, 'tasks/create_task.html', context=context)

@login_required
def detail_task(request, uuid):
    try:
        task = get_object_or_404(Task, uuid=uuid)
    except:
        raise Http404('Такой задачи не существует')

    context = {
        'task': task,
    }
    return render(request, 'tasks/task_detail.html', context=context)

@login_required
def delete_task(request, uuid):
    try:
        task = get_object_or_404(Task, uuid=uuid)
    except:
        raise Http404('Такой задачи не существует')

    task.delete()
    return redirect('/')

templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div style="display:flex">
  <div class="card text-dark bg-light mb-3" style="min-width: 400px; margin-left: 30px; padding:30px">
    <img src="{{ profile.avatar.url }}"/>
    <h3>Пользователь: {{ profile.first_name }} {{ profile.last_name }}</h3>
    <h3>telegram: {{ profile.telegram }}</h3>
    <h3>Всего задач: {{ profile.tasks_active }}</h3>
    <h3>Выполнено задач: {{ profile.tasks_completed }}</h3>
  </div>

<table>
  <thead>
    <tr>
    <th scope="col" style="text-align:center;">Активные задачи</th>
    <th scope="col" style="text-align:center;">Выполненные задачи</th>
    </tr>
  </thead>
  <tbody>
<td>
  <div style="display: grid; grid-template-columns: 30rem 30rem;">
  {% for task in tasks %}
  {% if task.status != 'completed' %}
      <div class="card text-dark bg-light mb-3" style="margin-left: 30px;">
          <div class="card-header"><h2 class="card-title">{{ task.name }}</h2></div>
          <div class="card-body border-light mb-3">
                <p class="card-text">{{ task.description }}</p>
          </div>
              <div class="card-footer">
                  <table class="table">
                      <thead>
                        <tr>
                            <th scope="col">Статус задачи</th>
                            <th scope="col">Автор</th>
                            <th scope="col">Исполнитель</th>
                        </tr>
                      </thead>
                      <tbody>
                            {% if task.status == 'not_started' %}
                                <td class="table-warning">Не начата
                            {% elif task.status == 'started' %}
                                <td class="table-success">Начата
                            {% elif task.status == 'completed' %}
                                <td class="table-secondary">Закрыта
                            {% elif task.status == 'reopened' %}
                                <td class="table-danger">Переоткрыта
                            {% endif %}
                        </td>
                      <td>{{ task.author }}</td>
                      <td>{{ task.executor }}</td>
                      </tbody>
                  </table>

                <p class="card-text">Дата создания задачи: {{ task.date_created|date:"f d/m/y" }}</p>
                <p class="card-text">Дата изменения задачи: {{ task.date_updated|date:"f d/m/y" }}</p>
                <a class="btn btn-primary" href="/edit{{ task.get_absolute_url }}">Редактировать</a>
          </div>
      </div>
  {% endif %}
{% endfor %}
  </div>
  </td>

<td>
  <div style="display: grid; grid-template-columns: 30rem 30rem; margin-left:100px">
  {% for task in tasks %}
    {% if task.status == 'completed' %}
      <div class="card text-dark bg-light mb-3" style="margin-left: 30px;">
          <div class="card-header"><h2 class="card-title">{{ task.name }}</h2></div>
          <div class="card-body border-light mb-3">
                <p class="card-text">{{ task.description }}</p>
          </div>
              <div class="card-footer">
                  <table class="table">
                      <thead>
                        <tr>
                            <th scope="col">Статус задачи</th>
                            <th scope="col">Автор</th>
                            <th scope="col">Исполнитель</th>
                        </tr>
                      </thead>
                      <tbody>
                            {% if task.status == 'not_started' %}
                                <td class="table-warning">Не начата
                            {% elif task.status == 'started' %}
                                <td class="table-success">Начата
                            {% elif task.status == 'completed' %}
                                <td class="table-secondary">Закрыта
                            {% elif task.status == 'reopened' %}
                                <td class="table-danger">Переоткрыта
                            {% endif %}
                        </td>
                      <td>{{ task.author }}</td>
                      <td>{{ task.executor }}</td>
                      </tbody>
                  </table>

                <p class="card-text">Дата создания задачи: {{ task.date_created|date:"f d/m/y" }}</p>
                <p class="card-text">Дата изменения задачи: {{ task.date_updated|date:"f d/m/y" }}</p>
                <a class="btn btn-primary" href="/edit{{ task.get_absolute_url }}">Редактировать</a>
          </div>
      </div>
    {% endif %}
{% endfor %}
      </div>
  </td>

  </tbody>
</table>
  </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

   <title>{% block title %}{% endblock title %}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'users:show_profile' %}">Профиль</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li>
                    <a class="nav-link" href="{% url 'tasks:create_task' %}">Создать задачу</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">Все задачи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tasks:completed_list_tasks' %}">Завершенные задачи</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    {% block content %}
    {% endblock content %}
</body>
    {% block script %}
    {% endblock script %}

</html>

templates/tasks/completed_task_list.html
{% extends 'base.html' %}
{% block title %}Task List{% endblock title %}
{% block content %}

<div style="display: grid; grid-template-columns: 42rem 42rem 42rem 42rem;">
    {% for task in tasks %}
      <div class="card text-dark bg-light mb-3" style="width: 40rem; margin-left: 30px; display: inline-block;">
          <div class="card-header"><h2 class="card-title">{{ task.name }}</h2></div>
          <div class="card-body border-light mb-3">
                <p class="card-text">{{ task.description }}</p>
          </div>
              <div class="card-footer">
                  <table class="table">
                      <thead>
                        <tr>
                            <th scope="col">Статус задачи</th>
                            <th scope="col">Автор</th>
                            <th scope="col">Исполнитель</th>
                        </tr>
                      </thead>
                      <tbody>
                            {% if task.status == 'not_started' %}
                                <td class="table-warning">Не начата
                            {% elif task.status == 'started' %}
                                <td class="table-success">Начата
                            {% elif task.status == 'completed' %}
                                <td class="table-secondary">Закрыта
                            {% elif task.status == 'reopened' %}
                                <td class="table-danger">Переоткрыта
                            {% endif %}
                        </td>
                      <td>{{ task.author }}</td>
                      <td>{{ task.executor }}</td>
                      </tbody>
                  </table>

                <p class="card-text">Дата создания задачи: {{ task.date_created|date:"f d/m/y" }}</p>
                <p class="card-text">Дата заверщения задачи: {{ task.date_completed|date:"f d/m/y" }}</p>
                <a class="btn btn-primary" href="{{ task.get_absolute_url }}">Подробнее</a>
                <a class="btn btn-primary" href="/edit{{ task.get_absolute_url }}">Редактировать</a>
          </div>
      </div>
    {% endfor %}
    </div>
{% endblock content %}

templates/tasks/create_task.html
{% extends 'base.html' %}

{% block content %}
<div class="card text-dark bg-light mb-3" style="width: 40rem; margin-left: 30px; padding:30px">
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type = "submit" value = "submit">
    </form>
</div>
{% endblock content %}

templates/tasks/task_detail.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{ task.name }}</h1>
  <h2>{{ task.description }}</h2>
  <h2><a href="/edit{{ task.get_absolute_url }}">Редактировать задачу</a></h2>
{% endblock content %}

templates/tasks/task_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="card text-dark bg-light mb-3" style="width: 40rem; margin-left: 30px; padding:30px">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Изменить">
        <a href="delete/" class="btn btn-danger">Удалить</a>
    </form>
</div>
{% endblock content %}

templates/tasks/task_list.html
{% extends 'base.html' %}
{% block title %}Task List{% endblock title %}
{% block content %}
<div style="display: grid; grid-template-columns: 42rem 42rem 42rem 42rem">
    {% for task in tasks %}
      <div class="card text-dark bg-light mb-3" style="width: 40rem; margin-left: 30px; display: inline-block;">
          <div class="card-header"><h2 class="card-title">{{ task.name }}</h2></div>
          <div class="card-body border-light mb-3">
                <p class="card-text">{{ task.description }}</p>
          </div>
              <div class="card-footer">
                  <table class="table">
                      <thead>
                        <tr>
                            <th scope="col">Статус задачи</th>
                            <th scope="col">Автор</th>
                            <th scope="col">Исполнитель</th>
                        </tr>
                      </thead>
                      <tbody>
                            {% if task.status == 'not_started' %}
                                <td class="table-warning">Не начата
                            {% elif task.status == 'started' %}
                                <td class="table-success">Начата
                            {% elif task.status == 'completed' %}
                                <td class="table-secondary">Закрыта
                            {% elif task.status == 'reopened' %}
                                <td class="table-danger">Переоткрыта
                            {% endif %}
                        </td>
                      <td>{{ task.author__first_name }}</td>
                      <td>{{ task.executor }}</td>
                      </tbody>
                  </table>

                <p class="card-text">Дата создания задачи: {{ task.date_created|date:"f d/m/y" }}</p>
                <p class="card-text">Дата изменения задачи: {{ task.date_updated|date:"f d/m/y" }}</p>
                <a class="btn btn-primary" href="/edit{{ task.get_absolute_url }}">Редактировать</a>
          </div>
      </div>
    {% endfor %}
    </div>
{% endblock content %}